import { GraphQLScalarType, Kind } from "graphql";
import { prisma } from "../db/prisma";
import { encodeBase62 } from "../utils/base62";

/**
 * Custom DateTime scalar. Serializes Date <-> ISO string.
 */
const dateTimeScalar = new GraphQLScalarType({
  name: "DateTime",
  description: "ISO-8601 DateTime",
  serialize(value: unknown): string {
    if (!(value instanceof Date)) {
      throw new Error("DateTime scalar can only serialize Date objects");
    }
    return value.toISOString();
  },
  parseValue(value: unknown): Date {
    if (typeof value !== "string") {
      throw new Error("DateTime scalar must be a string");
    }
    return new Date(value);
  },
  parseLiteral(ast): Date {
    if (ast.kind !== Kind.STRING) {
      throw new Error("DateTime scalar must be a string literal");
    }
    return new Date(ast.value);
  },
});

/**
 * Validate that a string is an http(s) URL. We intentionally do NOT
 * try to validate that the URL is reachable, only that it's well-formed.
 * Reachability checks belong in a separate validation pass or background job.
 */
function isValidUrl(s: string): boolean {
  try {
    const url = new URL(s);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

export const resolvers = {
  DateTime: dateTimeScalar,

  Url: {
    // BigInt id -> string for GraphQL ID type
    id: (parent: { id: bigint }) => parent.id.toString(),
  },

  Query: {
    getUrl: async (_: unknown, args: { shortCode: string }) => {
      return prisma.url.findUnique({
        where: { shortCode: args.shortCode },
      });
    },
  },

  Mutation: {
    createShortUrl: async (
      _: unknown,
      args: { longUrl: string; expiresAt?: Date },
    ) => {
      if (!isValidUrl(args.longUrl)) {
        throw new Error("longUrl must be a valid http(s) URL");
      }

      // Reserve the next id from the Postgres sequence BEFORE inserting.
      // This lets us compute the shortCode and insert the row in a single
      // operation, no placeholder, no update step.
      //
      // $queryRaw returns an array of rows. The result of nextval() comes
      // back as a BigInt because the underlying column is BIGINT.
      const result = await prisma.$queryRaw<Array<{ nextval: bigint }>>`
        SELECT nextval('urls_id_seq') AS nextval
      `;
      const nextId = result[0].nextval;
      const shortCode = encodeBase62(nextId);

      // Single insert with the real id and shortCode.
      return prisma.url.create({
        data: {
          id: nextId,
          shortCode,
          longUrl: args.longUrl,
          expiresAt: args.expiresAt ?? null,
        },
      });
    },

    deleteShortUrl: async (_: unknown, args: { shortCode: string }) => {
      try {
        await prisma.url.delete({ where: { shortCode: args.shortCode } });
        return true;
      } catch {
        // Prisma throws if the row doesn't exist. We treat that as "not deleted".
        return false;
      }
    },
  },
};

/**
 * The two-step insert pattern -
 * The counter-based approach requires the ID before we can compute the short code, but the ID is generated by the DB on insert. So we either:
 * 1. Insert with a placeholder, then update with the encoded ID (what I'm doing).
 * 2. Use a Postgres sequence and call nextval() before insert to reserve an ID, then insert with the real shortCode in one shot.
 * 3. Generate IDs application-side (Snowflake, ULID, etc.) and don't rely on DB auto-increment.
 */
